/** Chemins Lottie par thème de section (fichiers dans /public/lottie). */
export const LOTTIE = {
  orbit: '/lottie/orbit.json',
  scroll: '/lottie/scroll.json',
  success: '/lottie/success.json',
  web: '/lottie/web.json',
  shop: '/lottie/shop.json',
  phone: '/lottie/phone.json',
  shield: '/lottie/shield.json',
  chat: '/lottie/chat.json',
  rocket: '/lottie/rocket.json',
  design: '/lottie/design.json',
  money: '/lottie/money.json',
  team: '/lottie/team.json',
  error: '/lottie/error.json',
  offline: '/lottie/offline.json',
  search: '/lottie/search.json',
  growth: '/lottie/growth.json',
  mail: '/lottie/mail.json',
  code: '/lottie/code.json',
  star: '/lottie/star.json',
  calc: '/lottie/calc.json',
  process: '/lottie/process.json',
  tools: '/lottie/tools.json',
  support: '/lottie/support.json',
  review: '/lottie/review.json',
  empty: '/lottie/empty.json',
}
